name: planif_urbaine_sud
channels:
  - conda-forge
dependencies:
  - contextily
  - geopandas
  - geopy
  - ipykernel
  - matplotlib
  - openpyxl
  - pandas
  - pip
  - pre-commit
  - python=3.11
  - seaborn
  - osmnx
  - shapely
  - rasterio
  - rasterstats
  - pip:
      - jupyter-book
      - esri2gpd
